/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feedback;

import java.sql.Connection;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author BHAVYA
 */
public class FeedBack_ extends javax.swing.JFrame {

    /**
     * Creates new form FeedBack_
     */
    public FeedBack_() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        A1 = new javax.swing.JRadioButton();
        A2 = new javax.swing.JRadioButton();
        A3 = new javax.swing.JRadioButton();
        A4 = new javax.swing.JRadioButton();
        B1 = new javax.swing.JRadioButton();
        B2 = new javax.swing.JRadioButton();
        B3 = new javax.swing.JRadioButton();
        B4 = new javax.swing.JRadioButton();
        C1 = new javax.swing.JRadioButton();
        C2 = new javax.swing.JRadioButton();
        C3 = new javax.swing.JRadioButton();
        C4 = new javax.swing.JRadioButton();
        D1 = new javax.swing.JRadioButton();
        D2 = new javax.swing.JRadioButton();
        D3 = new javax.swing.JRadioButton();
        D4 = new javax.swing.JRadioButton();
        E1 = new javax.swing.JRadioButton();
        E2 = new javax.swing.JRadioButton();
        E3 = new javax.swing.JRadioButton();
        E4 = new javax.swing.JRadioButton();
        F1 = new javax.swing.JRadioButton();
        F2 = new javax.swing.JRadioButton();
        F3 = new javax.swing.JRadioButton();
        F4 = new javax.swing.JRadioButton();
        G1 = new javax.swing.JRadioButton();
        G2 = new javax.swing.JRadioButton();
        H1 = new javax.swing.JRadioButton();
        H2 = new javax.swing.JRadioButton();
        H3 = new javax.swing.JRadioButton();
        I1 = new javax.swing.JRadioButton();
        I2 = new javax.swing.JRadioButton();
        I3 = new javax.swing.JRadioButton();
        J1 = new javax.swing.JRadioButton();
        J2 = new javax.swing.JRadioButton();
        J3 = new javax.swing.JRadioButton();
        J4 = new javax.swing.JRadioButton();
        K1 = new javax.swing.JRadioButton();
        K2 = new javax.swing.JRadioButton();
        K3 = new javax.swing.JRadioButton();
        K4 = new javax.swing.JRadioButton();
        L1 = new javax.swing.JRadioButton();
        L2 = new javax.swing.JRadioButton();
        L3 = new javax.swing.JRadioButton();
        M1 = new javax.swing.JRadioButton();
        M2 = new javax.swing.JRadioButton();
        M3 = new javax.swing.JRadioButton();
        N1 = new javax.swing.JRadioButton();
        N2 = new javax.swing.JRadioButton();
        N3 = new javax.swing.JRadioButton();
        O1 = new javax.swing.JRadioButton();
        O2 = new javax.swing.JRadioButton();
        O3 = new javax.swing.JRadioButton();
        P1 = new javax.swing.JRadioButton();
        P2 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel2.setMinimumSize(new java.awt.Dimension(725, 1176));
        jPanel2.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jPanel2MouseWheelMoved(evt);
            }
        });
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FEED-BACK  FORM");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 10, 590, 70);

        jLabel6.setText("1. HOW WAS THE DAY ?");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(120, 100, 510, 30);

        jLabel7.setText("2. WAS THE ENVIRONMENT FRIENDLY ?");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(120, 160, 460, 30);

        jLabel8.setText("3. WAS THE STAFF/COLLEUGES FRIENDLY ?");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(120, 230, 370, 30);

        jLabel9.setText("4. WAS THE DAY PRODUCTIVE ?");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(120, 300, 420, 30);

        jLabel10.setText("5. DIDYOU LEARN SOMETHING NEW ?");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(120, 370, 520, 30);

        jLabel11.setText("6. DO YOU FEEL PRESSURE OF WORK ?");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(120, 440, 540, 30);

        jLabel12.setText("7. DO YOU HAVE YOUR LUNCH ?");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(120, 520, 430, 20);

        jLabel13.setText("8. DO YOU FIND ANY TROUBLE USING MACHINERY ?");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(120, 570, 490, 30);

        jLabel14.setText("9. DO YOU GET ADEQUATE BREAK BETWEEN THE WORK ?");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(120, 640, 470, 30);

        jLabel15.setText("10. WAS THE DAY BOREING ?");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(120, 710, 410, 20);

        jLabel16.setText("11. WAS THE DAY STRESS-FULL ?");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(120, 770, 400, 30);

        jLabel17.setText("12. WERE THE SYSTEM(S) WORKING PROPERLY ?");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(120, 830, 410, 30);

        jLabel18.setText("13. DO YOU SIT ON THE CHAIR FOR THE LONG DURATION ?");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(120, 890, 410, 30);

        jLabel19.setText("14. IS THERE PROPER LIGHTNING ON YOUR DESK ?");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(120, 950, 440, 30);

        jLabel20.setText("15. WAS THE TOILET(S) CLEAN ?");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(120, 1000, 430, 30);

        jLabel21.setText("16. WERE THE TOILETRIES AVAILABLE ?");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(120, 1060, 390, 30);

        A1.setText("BAD");
        jPanel2.add(A1);
        A1.setBounds(130, 130, 45, 23);

        A2.setText("GOOD");
        jPanel2.add(A2);
        A2.setBounds(240, 130, 93, 23);

        A3.setText("V.GOOD");
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });
        jPanel2.add(A3);
        A3.setBounds(370, 130, 65, 23);

        A4.setText("EXELLENT");
        A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4ActionPerformed(evt);
            }
        });
        jPanel2.add(A4);
        A4.setBounds(500, 130, 73, 23);

        B1.setText("NO");
        jPanel2.add(B1);
        B1.setBounds(130, 200, 41, 23);

        B2.setText("LITTLE BIT");
        jPanel2.add(B2);
        B2.setBounds(230, 200, 77, 23);

        B3.setText("MOSTLY");
        jPanel2.add(B3);
        B3.setBounds(370, 200, 65, 23);

        B4.setText("EXTREAMLY");
        jPanel2.add(B4);
        B4.setBounds(500, 200, 83, 23);

        C1.setText("NOT");
        jPanel2.add(C1);
        C1.setBounds(130, 270, 47, 23);

        C2.setText("LITTLE");
        jPanel2.add(C2);
        C2.setBounds(230, 270, 57, 23);

        C3.setText("MOSTLY");
        jPanel2.add(C3);
        C3.setBounds(370, 270, 65, 23);

        C4.setText("EXTREAMLY");
        jPanel2.add(C4);
        C4.setBounds(500, 270, 83, 23);

        D1.setText("NOT");
        jPanel2.add(D1);
        D1.setBounds(130, 340, 93, 23);

        D2.setText("LITTLE BIT");
        jPanel2.add(D2);
        D2.setBounds(230, 340, 77, 23);

        D3.setText("MOSTLY");
        jPanel2.add(D3);
        D3.setBounds(370, 340, 65, 23);

        D4.setText("EXTREAMLY");
        jPanel2.add(D4);
        D4.setBounds(500, 340, 83, 23);

        E1.setText("NOT");
        jPanel2.add(E1);
        E1.setBounds(120, 410, 47, 23);

        E2.setText("LITTLE");
        jPanel2.add(E2);
        E2.setBounds(230, 410, 57, 23);

        E3.setText("MOSTLY");
        jPanel2.add(E3);
        E3.setBounds(370, 410, 93, 23);

        E4.setText("EXTREAMLY");
        jPanel2.add(E4);
        E4.setBounds(500, 410, 83, 23);

        F1.setText("NO");
        jPanel2.add(F1);
        F1.setBounds(120, 480, 93, 23);

        F2.setText("LITTLE");
        jPanel2.add(F2);
        F2.setBounds(230, 480, 57, 23);

        F3.setText("MOSTLY");
        jPanel2.add(F3);
        F3.setBounds(370, 480, 93, 23);

        F4.setText("EXTREAMLY");
        jPanel2.add(F4);
        F4.setBounds(500, 480, 83, 23);

        G1.setText("NO");
        jPanel2.add(G1);
        G1.setBounds(120, 550, 41, 23);

        G2.setText("YES");
        jPanel2.add(G2);
        G2.setBounds(230, 550, 43, 23);

        H1.setText("NO");
        jPanel2.add(H1);
        H1.setBounds(120, 610, 41, 23);

        H2.setText("LITTLE");
        jPanel2.add(H2);
        H2.setBounds(230, 610, 57, 23);

        H3.setText("YES");
        H3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H3ActionPerformed(evt);
            }
        });
        jPanel2.add(H3);
        H3.setBounds(380, 610, 93, 23);

        I1.setText("NO");
        jPanel2.add(I1);
        I1.setBounds(120, 680, 41, 23);

        I2.setText("MOSTLY");
        jPanel2.add(I2);
        I2.setBounds(230, 680, 65, 23);

        I3.setText("YES");
        jPanel2.add(I3);
        I3.setBounds(380, 680, 43, 23);

        J1.setText("YES");
        jPanel2.add(J1);
        J1.setBounds(120, 740, 43, 23);

        J2.setText("LITTLE");
        jPanel2.add(J2);
        J2.setBounds(230, 740, 57, 23);

        J3.setText("MOSTLY");
        J3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J3ActionPerformed(evt);
            }
        });
        jPanel2.add(J3);
        J3.setBounds(380, 740, 93, 23);

        J4.setText("EXCITING");
        jPanel2.add(J4);
        J4.setBounds(500, 740, 93, 23);

        K1.setText("YES");
        jPanel2.add(K1);
        K1.setBounds(120, 810, 43, 23);

        K2.setText("LITTLE");
        K2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K2ActionPerformed(evt);
            }
        });
        jPanel2.add(K2);
        K2.setBounds(220, 810, 57, 23);

        K3.setText("MOSTLY");
        jPanel2.add(K3);
        K3.setBounds(380, 810, 65, 23);

        K4.setText("EXTREAMLY");
        jPanel2.add(K4);
        K4.setBounds(500, 810, 83, 23);

        L1.setText("NO");
        jPanel2.add(L1);
        L1.setBounds(120, 870, 41, 23);

        L2.setText("MOSTLY");
        jPanel2.add(L2);
        L2.setBounds(220, 870, 65, 23);

        L3.setText("YES");
        jPanel2.add(L3);
        L3.setBounds(380, 870, 43, 23);

        M1.setText("YES");
        jPanel2.add(M1);
        M1.setBounds(120, 930, 43, 23);

        M2.setText("SOMETIMES");
        jPanel2.add(M2);
        M2.setBounds(220, 930, 83, 23);

        M3.setText("NOT OFTEN");
        jPanel2.add(M3);
        M3.setBounds(380, 930, 83, 23);

        N1.setText("NO");
        jPanel2.add(N1);
        N1.setBounds(120, 980, 41, 23);

        N2.setText("TO SOME EXTEND");
        jPanel2.add(N2);
        N2.setBounds(220, 980, 120, 23);

        N3.setText("PROPER");
        jPanel2.add(N3);
        N3.setBounds(380, 980, 65, 23);

        O1.setText("NO");
        jPanel2.add(O1);
        O1.setBounds(120, 1030, 41, 23);

        O2.setText("TO SOME EXTEND");
        jPanel2.add(O2);
        O2.setBounds(220, 1030, 120, 23);

        O3.setText("CLEAN");
        jPanel2.add(O3);
        O3.setBounds(380, 1030, 57, 23);

        P1.setText("NO");
        jPanel2.add(P1);
        P1.setBounds(110, 1090, 41, 23);

        P2.setText("YES");
        jPanel2.add(P2);
        P2.setBounds(220, 1090, 43, 23);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(310, 1120, 103, 31);

        jScrollBar1.setMaximum(1175);
        jPanel2.add(jScrollBar1);
        jScrollBar1.setBounds(650, 0, 17, 1150);

        getContentPane().add(jPanel2, "card3");

        jPanel1.setMinimumSize(new java.awt.Dimension(725, 1176));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FEED-BACK  FORM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 10, 590, 70);

        jLabel2.setText("NAME:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 130, 70, 30);

        jLabel3.setText("DEPARTMENT:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 230, 90, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(260, 130, 290, 30);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(260, 180, 290, 30);

        jLabel4.setText("E-MAIL:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 180, 60, 30);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(260, 230, 290, 30);

        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(320, 310, 130, 30);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       /* String name=jTextField1.getText();
        String email=jTextField2.getText();
        String dept=jTextField3.getText();
        */
        jPanel2.setVisible(true);
        


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A3ActionPerformed

    private void A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A4ActionPerformed

    private void H3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_H3ActionPerformed

    private void J3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J3ActionPerformed

    private void K2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_K2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  
        String q1="empty";
        String q2="empty",q3="empty",q4="empty",q5="empty",q6="e",q7="e",q8="e",q9="e",q10="e",q11="e",q12="e",q13="e",q14="e",q15="e",q16="empty";
        
        
         try{
             
             Connection con=factory.Confac.getcon();
            Statement stmt=con.createStatement();  
        
        ButtonGroup a1=new ButtonGroup();
        a1.add(A1);a1.add(A2);a1.add(A3);a1.add(A4);
       
         if(A1.isSelected())
        {
         q1 = "A1";
        
        }
        else if(A2.isSelected())
        {
          q1="A2";
        }
        else if(A3.isSelected())
        {
         q1="A3";
        }
        else if(A4.isSelected())
        {
          q1="A4";
        }
         else
        {
        JOptionPane.showMessageDialog(this,"option not selected");
        }
        
         ButtonGroup b1=new ButtonGroup();
        b1.add(B1);b1.add(B2);b1.add(B3);b1.add(B4);
        if(B1.isSelected())
        {
         q2="B1";
        }
        else if(B2.isSelected())
        {
         q2="B2";
        }
        else if(B3.isSelected())
        {
         q2="B3";
        }
        else if(B4.isSelected())
        {
         q2="B4";
        }
        
        
         ButtonGroup c1=new ButtonGroup();
        c1.add(C1);c1.add(C2);c1.add(C3);c1.add(C4);
        if(C1.isSelected())
        {
         q3="C1";
        }
        else if(C2.isSelected())
        {
         q3="C2";
        }
        else if(C3.isSelected())
        {
          q3="C3";
        }
        else if(C4.isSelected())
        {
         q3="C4";
        }
        
        
         ButtonGroup d1=new ButtonGroup();
        d1.add(D1);d1.add(D2);d1.add(D3);d1.add(D4);
        if(D1.isSelected())
        {
         q4="D1";
        }
        else if(D2.isSelected())
        {
         q4="D2";
        }
        else if(D3.isSelected())
        {
        q4="D3";
        }
        else if(D4.isSelected())
        {
         q4="D4";
        }
        
        
         ButtonGroup e1=new ButtonGroup();
        e1.add(E1);e1.add(E2);e1.add(E3);e1.add(E4);
        if(E1.isSelected())
        {
         q5="E1";
        }
        else if(E2.isSelected())
        {
        q5="E2";
        }
        else if(E3.isSelected())
        {
         q5="E3";
        }
        else if(E4.isSelected())
        {
         q5="E4";
        }
        
        
         ButtonGroup f1=new ButtonGroup();
        f1.add(F1);f1.add(F2);f1.add(F3);f1.add(F4);
        if(F1.isSelected())
        {
         q6="F1";
        }
        else if(F2.isSelected())
        {
         q6="F2";
        }
        else if(F3.isSelected())
        {
         q6="F3";
        }
        else if(F4.isSelected())
        {
         q6="F4";
        }
        
        
         ButtonGroup g1=new ButtonGroup();
        g1.add(G1);g1.add(G2);
        if(G1.isSelected())
        {
         q7="G1";
        }
        else if(G2.isSelected())
        {
         q7="G2";
        }
        
        
        
         ButtonGroup h1=new ButtonGroup();
        h1.add(H1);h1.add(H2);h1.add(H3);
        if(H1.isSelected())
        {
         q8="H1";
        }
        else if(H2.isSelected())
        {
         q8="H2";
        }
        else if(H3.isSelected())
        {
         q8="H3";
        }
       
        
        
         ButtonGroup i1=new ButtonGroup();
        i1.add(I1);i1.add(I2);i1.add(I3);
        if(I1.isSelected())
        {
         q9="I1";
        }
        else if(I2.isSelected())
        {
         q9="I2";
        }
        else if(I3.isSelected())
        {
         q9="I3";
        }
       
        
        
         ButtonGroup j1=new ButtonGroup();
        j1.add(J1);j1.add(J2);j1.add(J3);j1.add(J4);
        if(J1.isSelected())
        {
         q10="J1";
        }
        else if(J2.isSelected())
        {
         q10="J2";
        }
        else if(J3.isSelected())
        {
         q10="J3";
        }
        else if(J4.isSelected())
        {
         q10="J4";
        }
        
        
         ButtonGroup k1=new ButtonGroup();
        k1.add(K1);k1.add(K2);k1.add(K3);k1.add(K4);
        if(K1.isSelected())
        {
         q11="K1";
        }
        else if(K2.isSelected())
        {
         q11="K2";
        }
        else if(K3.isSelected())
        {
         q11="K3";
        }
        else if(K4.isSelected())
        {
         q11="K4";
        }
        
        
         ButtonGroup l1=new ButtonGroup();
        l1.add(L1);l1.add(L2);l1.add(L3);
        if(L1.isSelected())
        {
         q12="L1";
        }
        else if(L2.isSelected())
        {
         q12="L2";
        }
        else if(L3.isSelected())
        {
         q12="L3";
        }
       
        
        
         ButtonGroup m1=new ButtonGroup();
        m1.add(M1);m1.add(M2);m1.add(M3);
        if(M1.isSelected())
        {
         q13="M1";
        }
        else if(M2.isSelected())
        {
        q13="M2";
        }
        else if(M3.isSelected())
        {
         q13="M3";
        }
       
        
        
         ButtonGroup n1=new ButtonGroup();
        n1.add(N1);n1.add(N2);n1.add(N3);
        if(N1.isSelected())
        {
         q14="N1";
        }
        else if(N2.isSelected())
        {
         q14="N2";
        }
        else if(N3.isSelected())
        {
         q14="N3";
        }
       
        
        
         ButtonGroup o1=new ButtonGroup();
        o1.add(O1);o1.add(O2);o1.add(O3);
        if(O1.isSelected())
        {
         q15="O1";
        }
        else if(O2.isSelected())
        {
        q15="O2";
        }
        else if(O3.isSelected())
        {
         q15="O3";
        }
       
        
        
         ButtonGroup p1=new ButtonGroup();
        p1.add(P1);p1.add(P2);
        if(P1.isSelected())
        {
        q16="P1";
        }
        else if(P2.isSelected())
        {
         q16="P2";
        }
       
        
         stmt.executeUpdate("insert into feed(q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16) values('"+q1+"','"+q2+"','"+q3+"','"+q4+"','"+q5+"','"+q6+"','"+q7+"','"+q8+"','"+q9+"')");
            JOptionPane.showMessageDialog(this," data submitted!");
       
         }
        
         catch(Exception e)
        {
            System.out.println("submit correct data "+e);
            JOptionPane.showMessageDialog(this,"wrong data entered!");
            
        
        }
        
        
        
        
        
        
        



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPanel2MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jPanel2MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseWheelMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeedBack_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeedBack_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeedBack_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeedBack_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FeedBack_().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A1;
    private javax.swing.JRadioButton A2;
    private javax.swing.JRadioButton A3;
    private javax.swing.JRadioButton A4;
    private javax.swing.JRadioButton B1;
    private javax.swing.JRadioButton B2;
    private javax.swing.JRadioButton B3;
    private javax.swing.JRadioButton B4;
    private javax.swing.JRadioButton C1;
    private javax.swing.JRadioButton C2;
    private javax.swing.JRadioButton C3;
    private javax.swing.JRadioButton C4;
    private javax.swing.JRadioButton D1;
    private javax.swing.JRadioButton D2;
    private javax.swing.JRadioButton D3;
    private javax.swing.JRadioButton D4;
    private javax.swing.JRadioButton E1;
    private javax.swing.JRadioButton E2;
    private javax.swing.JRadioButton E3;
    private javax.swing.JRadioButton E4;
    private javax.swing.JRadioButton F1;
    private javax.swing.JRadioButton F2;
    private javax.swing.JRadioButton F3;
    private javax.swing.JRadioButton F4;
    private javax.swing.JRadioButton G1;
    private javax.swing.JRadioButton G2;
    private javax.swing.JRadioButton H1;
    private javax.swing.JRadioButton H2;
    private javax.swing.JRadioButton H3;
    private javax.swing.JRadioButton I1;
    private javax.swing.JRadioButton I2;
    private javax.swing.JRadioButton I3;
    private javax.swing.JRadioButton J1;
    private javax.swing.JRadioButton J2;
    private javax.swing.JRadioButton J3;
    private javax.swing.JRadioButton J4;
    private javax.swing.JRadioButton K1;
    private javax.swing.JRadioButton K2;
    private javax.swing.JRadioButton K3;
    private javax.swing.JRadioButton K4;
    private javax.swing.JRadioButton L1;
    private javax.swing.JRadioButton L2;
    private javax.swing.JRadioButton L3;
    private javax.swing.JRadioButton M1;
    private javax.swing.JRadioButton M2;
    private javax.swing.JRadioButton M3;
    private javax.swing.JRadioButton N1;
    private javax.swing.JRadioButton N2;
    private javax.swing.JRadioButton N3;
    private javax.swing.JRadioButton O1;
    private javax.swing.JRadioButton O2;
    private javax.swing.JRadioButton O3;
    private javax.swing.JRadioButton P1;
    private javax.swing.JRadioButton P2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
